// Generated by gencpp from file opencv_isyn/isyn_data.msg
// DO NOT EDIT!


#ifndef OPENCV_ISYN_MESSAGE_ISYN_DATA_H
#define OPENCV_ISYN_MESSAGE_ISYN_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <opencv_isyn/isyn.h>

namespace opencv_isyn
{
template <class ContainerAllocator>
struct isyn_data_
{
  typedef isyn_data_<ContainerAllocator> Type;

  isyn_data_()
    : header()
    , image_header()
    , opencv_isyn()  {
    }
  isyn_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , opencv_isyn(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::opencv_isyn::isyn_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::opencv_isyn::isyn_<ContainerAllocator> >::other >  _opencv_isyn_type;
  _opencv_isyn_type opencv_isyn;





  typedef boost::shared_ptr< ::opencv_isyn::isyn_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_isyn::isyn_data_<ContainerAllocator> const> ConstPtr;

}; // struct isyn_data_

typedef ::opencv_isyn::isyn_data_<std::allocator<void> > isyn_data;

typedef boost::shared_ptr< ::opencv_isyn::isyn_data > isyn_dataPtr;
typedef boost::shared_ptr< ::opencv_isyn::isyn_data const> isyn_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_isyn::isyn_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_isyn::isyn_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opencv_isyn

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'opencv_isyn': ['/home/ksshin/catkin_ws/src/opencv_isyn/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opencv_isyn::isyn_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_isyn::isyn_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_isyn::isyn_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_isyn::isyn_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_isyn::isyn_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_isyn::isyn_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_isyn::isyn_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e35d1c33611162fb0cd98a5345208bd6";
  }

  static const char* value(const ::opencv_isyn::isyn_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe35d1c33611162fbULL;
  static const uint64_t static_value2 = 0x0cd98a5345208bd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_isyn::isyn_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_isyn/isyn_data";
  }

  static const char* value(const ::opencv_isyn::isyn_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_isyn::isyn_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Header image_header\n\
isyn[] opencv_isyn\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: opencv_isyn/isyn\n\
int32 isyn_stat\n\
int32 detect_person_num\n\
\n\
";
  }

  static const char* value(const ::opencv_isyn::isyn_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_isyn::isyn_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.opencv_isyn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isyn_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_isyn::isyn_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_isyn::isyn_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "opencv_isyn[]" << std::endl;
    for (size_t i = 0; i < v.opencv_isyn.size(); ++i)
    {
      s << indent << "  opencv_isyn[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::opencv_isyn::isyn_<ContainerAllocator> >::stream(s, indent + "    ", v.opencv_isyn[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_ISYN_MESSAGE_ISYN_DATA_H
